# Generated by Django 6.1 on 2026-09-01 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Legal name of the charitable organization', max_length=255, unique=True, verbose_name='organization name')),
                ('description', models.TextField(blank=True, help_text='Description of the organization mission and activities', verbose_name='description')),
                ('email', models.EmailField(help_text='Primary contact email for the organization', max_length=255, verbose_name='contact email')),
                ('phone', models.CharField(blank=True, help_text='Primary contact phone number', max_length=50, verbose_name='phone number')),
                ('website', models.URLField(blank=True, help_text='Organization website URL', max_length=500, verbose_name='website')),
                ('address', models.CharField(blank=True, help_text='Street address of the organization', max_length=500, verbose_name='street address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state/province')),
                ('country', models.CharField(default='United States', help_text='Country where the organization is registered', max_length=100, verbose_name='country')),
                ('registration_number', models.CharField(db_index=True, help_text='Government registration/charity number', max_length=100, unique=True, verbose_name='registration number')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Current verification status of the organization', max_length=20, verbose_name='verification status')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when organization was verified', null=True, verbose_name='verified at')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if verification status is REJECTED', verbose_name='rejection reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('owner', models.OneToOneField(help_text='Charity user who owns this organization', limit_choices_to={'role': 'CHARITY'}, on_delete=django.db.models.deletion.PROTECT, related_name='charity_organization', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'charity organization',
                'verbose_name_plural': 'charity organizations',
                'db_table': 'charity_organizations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['verification_status', 'created_at'], name='ix_charity_org_status_date'), models.Index(fields=['country', 'city'], name='ix_charity_org_location')],
                'constraints': [models.UniqueConstraint(fields=('owner',), name='uq_charity_org_owner', violation_error_message='A charity user can only own one organization.')],
            },
        ),
    ]
