# Generated by Django 6.1 on 2026-09-01 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charityorganization',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when verification was reviewed by admin', null=True, verbose_name='reviewed at'),
        ),
        migrations.AddField(
            model_name='charityorganization',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who reviewed the verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charity_verifications_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by'),
        ),
        migrations.AddField(
            model_name='charityorganization',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when organization was submitted for verification', null=True, verbose_name='submitted at'),
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit for verification'), ('APPROVE', 'Approve verification'), ('REJECT', 'Reject verification'), ('RESUBMIT', 'Resubmit after rejection')], db_index=True, max_length=20, verbose_name='action')),
                ('from_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], max_length=20, verbose_name='from status')),
                ('to_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], max_length=20, verbose_name='to status')),
                ('reason', models.TextField(blank=True, help_text='Reason for rejection or other notes', verbose_name='reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='charities.charityorganization', verbose_name='organization')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_actions', to=settings.AUTH_USER_MODEL, verbose_name='performed by')),
            ],
            options={
                'verbose_name': 'verification log',
                'verbose_name_plural': 'verification logs',
                'db_table': 'charity_verification_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='ix_verif_log_org_date')],
            },
        ),
    ]
