# Generated by Django 6.1 on 2026-09-01 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('charities', '0002_charityorganization_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField()),
                ('slots_available', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_opportunities', to='campaigns.campaign')),
                ('charity_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_opportunities', to='charities.charityorganization')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ATTENDED', 'Attended')], default='PENDING', max_length=20)),
                ('statement', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_applications', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='volunteers.volunteeropportunity')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddIndex(
            model_name='volunteeropportunity',
            index=models.Index(fields=['status', 'event_date'], name='volunteers__status_a602d5_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteeropportunity',
            index=models.Index(fields=['charity_organization'], name='volunteers__charity_a3690a_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerapplication',
            index=models.Index(fields=['status'], name='volunteers__status_664c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerapplication',
            index=models.Index(fields=['volunteer'], name='volunteers__volunte_14b021_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='volunteerapplication',
            unique_together={('opportunity', 'volunteer')},
        ),
    ]
