# Generated by Django 6.1 on 2026-09-05 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VERIFICATION_SUBMIT', 'Verification submitted'), ('VERIFICATION_APPROVE', 'Verification approved'), ('VERIFICATION_REJECT', 'Verification rejected'), ('VERIFICATION_RESUBMIT', 'Verification resubmitted'), ('CAMPAIGN_CREATED', 'Campaign created'), ('CAMPAIGN_UPDATED', 'Campaign updated'), ('CAMPAIGN_CANCELLED', 'Campaign cancelled'), ('CAMPAIGN_DELETED', 'Campaign deleted')], db_index=True, max_length=40, verbose_name='action')),
                ('resource_type', models.CharField(db_index=True, help_text='Django model name of the affected resource, e.g. CharityOrganization.', max_length=50, verbose_name='resource type')),
                ('resource_label', models.CharField(help_text='Human-readable label of the affected resource (e.g. organization name).', max_length=255, verbose_name='resource label')),
                ('detail', models.TextField(blank=True, help_text='Optional human-readable context for the event.', verbose_name='detail')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action (null if not applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='ix_audit_action_date'), models.Index(fields=['resource_type', 'resource_label'], name='ix_audit_resource')],
            },
        ),
    ]
