# Generated by Django 6.1 on 2026-09-01 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Donation amount in currency (must be greater than zero)', max_digits=12, verbose_name='amount')),
                ('currency', models.CharField(default='INR', help_text='ISO 4217 currency code, e.g. INR', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', help_text='Payment status of the donation', max_length=20, verbose_name='status')),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, help_text='Unique Razorpay order identifier', max_length=255, null=True, unique=True, verbose_name='Razorpay order ID')),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, help_text='Razorpay payment identifier upon successful capture', max_length=255, null=True, verbose_name='Razorpay payment ID')),
                ('razorpay_signature', models.CharField(blank=True, help_text='HMAC SHA256 payment signature from Razorpay', max_length=255, null=True, verbose_name='Razorpay signature')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Client or server idempotency key to prevent duplicate charges', max_length=255, null=True, unique=True, verbose_name='idempotency key')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Whether donor identity is hidden from public campaign feeds', verbose_name='is anonymous')),
                ('message', models.TextField(blank=True, help_text='Optional encouraging message or note to the campaign', max_length=1000, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('campaign', models.ForeignKey(help_text='Campaign receiving the donation', on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='campaigns.campaign', verbose_name='campaign')),
                ('donor', models.ForeignKey(help_text='User who made the donation', on_delete=django.db.models.deletion.PROTECT, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='donor')),
            ],
            options={
                'verbose_name': 'donation',
                'verbose_name_plural': 'donations',
                'db_table': 'donations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['donor', 'created_at'], name='ix_donation_donor_created'), models.Index(fields=['campaign', 'status'], name='ix_donation_campaign_status'), models.Index(fields=['status', 'created_at'], name='ix_donation_status_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cx_donation_amount_gt_zero', violation_error_message='Donation amount must be greater than zero.')],
            },
        ),
    ]
