# Generated by Django 6.1 on 2026-09-01 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charities', '0002_charityorganization_reviewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short public title for the campaign', max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the campaign and its purpose', max_length=5000, verbose_name='description')),
                ('category', models.CharField(choices=[('MEDICAL', 'Medical'), ('EDUCATION', 'Education'), ('DISASTER_RELIEF', 'Disaster Relief'), ('ENVIRONMENT', 'Environment'), ('ANIMALS', 'Animals'), ('COMMUNITY', 'Community'), ('CHILDREN', 'Children'), ('FOOD', 'Food & Hunger'), ('POVERTY', 'Poverty Alleviation'), ('OTHER', 'Other')], db_index=True, help_text='Category the campaign belongs to', max_length=30, verbose_name='category')),
                ('goal_amount', models.DecimalField(decimal_places=2, help_text='Target amount to raise (must be greater than zero)', max_digits=12, verbose_name='goal amount')),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount raised so far. Controlled by the donations domain — never writable through campaign endpoints.', max_digits=12, verbose_name='raised amount')),
                ('location', models.CharField(help_text='City/region where the campaign is based', max_length=255, verbose_name='location')),
                ('start_date', models.DateField(help_text='First day the campaign runs', verbose_name='start date')),
                ('end_date', models.DateField(help_text='Last day the campaign accepts donations', verbose_name='end date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', help_text='Current lifecycle state of the campaign', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('organization', models.ForeignKey(help_text='Charity organization running this campaign', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='charities.charityorganization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='ix_campaign_org_created'), models.Index(fields=['status', 'created_at'], name='ix_campaign_status_created'), models.Index(fields=['category', 'status'], name='ix_campaign_category_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('goal_amount__gt', 0)), name='cx_campaign_goal_gt_zero', violation_error_message='Goal amount must be greater than zero.'), models.CheckConstraint(condition=models.Q(('raised_amount__gte', 0)), name='cx_campaign_raised_gte_zero', violation_error_message='Raised amount cannot be negative.')],
            },
        ),
    ]
