# Generated by Django 6.1 on 2026-09-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image displayed with the campaign', null=True, upload_to='campaigns/', verbose_name='image'),
        ),
    ]
