# Generated by Django 6.1 on 2026-09-06 11:53

import campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image displayed with the campaign', null=True, upload_to=campaigns.models.campaign_image_upload_to, verbose_name='image'),
        ),
    ]
