# Generated by Django 6.1 on 2026-09-01 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('charities', '0002_charityorganization_reviewed_at_and_more'),
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('donation_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='campaigns.campaign')),
                ('charity_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='charities.charityorganization')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='donations.donation')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receipt_number'], name='receipts_re_receipt_840679_idx'), models.Index(fields=['created_at'], name='receipts_re_created_f612f6_idx')],
            },
        ),
    ]
